### ISSUE TITLE
Diet Restrictions are reversed. 

### ISSUE THREAD

**Issue by SpaceMeatball79** [Deadbones2000/Medieval-Origins#12] opened 2022-06-23 15:52 UTC
Origins that are supposed to be herbivores can only eat meat and vice-versa.

**Comment by silversilenc3** [comment] 2022-07-03 07:00
i've been having the same problem! specifically elf origin.

**Comment by BjornTjockPals** [comment] 2022-07-10 02:11
I looks fixed, except elves. I checked some origins (avian, bee, wolf, werewolf, demon, elf) and it looks like diet restrictions are as intended (except elves).

Tested on 1.19
medieval origins 4.1.1

**Comment by BjornTjockPals** [comment] 2022-07-16 17:35
Fixed in new update; can be closed.

**Closed** 2022-07-17 19:29 UTC
